import type {
  ArchiveEntry,
  AssetSlot,
  ProjectDefinition,
  SceneDefinition,
  SceneId,
  TeamMember,
} from './types';

export const TEAM: TeamMember[] = [
  { id: 'calin-nedelcu', name: 'Călin Nedelcu', discipline: 'Product & systems', portraitSrc: '/assets/membrii/CalinNedelcu.webp', status: 'needs-review' },
  { id: 'vlad-bostina', name: 'Vlad Boștină', discipline: 'Backend & 3D', portraitSrc: '/assets/membrii/VladBostina.webp', status: 'needs-review' },
  { id: 'andrei-cheroiu', name: 'Andrei Cheroiu', discipline: 'AI & computer vision', portraitSrc: '/assets/membrii/AndreiCheroiu.webp', status: 'needs-review' },
  { id: 'alex-istrate', name: 'Alex Istrate', discipline: 'Full-stack', portraitSrc: '/assets/membrii/AlexIstrate.webp', status: 'needs-review' },
  { id: 'cristian-buloi', name: 'Cristian Buloi', discipline: 'Design & frontend', portraitSrc: '/assets/membrii/CristianBuloi.webp', status: 'needs-review' },
  { id: 'vlad-colan', name: 'Vlad Colan', discipline: 'Games & 3D', portraitSrc: '/assets/membrii/VladColan.webp', status: 'needs-review' },
];

export const SCENES: SceneDefinition[] = [
  {
    id: 'signal',
    index: '00',
    navLabel: 'Start',
    eyebrow: 'C.N.I. Tudor Vianu / Bucharest',
    title: 'Transylvanian Bears',
    body: 'O echipă de informatică ce construiește produse, jocuri și cercetare. Fiecare proiect pornește dintr-o problemă reală și se termină cu ceva care poate fi testat.',
    align: 'left',
    tone: 'mineral',
    scrollVh: 150,
    asset: {
      id: 'world-observatory-dawn',
      kind: 'environment',
      status: 'placeholder',
      aspectRatio: '16:10',
      minimumSize: '2400x1500',
      subject: 'Observator-fortăreață secular, inspirat structural de incintele fortificate transilvănene.',
      composition: 'Blue hour, nucleu central lizibil, poarta în treimea dreaptă, spațiu negativ pentru titlu în stânga.',
      motionRole: 'Camera înaintează lent; un singur semnal ajunge la pivotul porții.',
      mobileTreatment: 'Crop 4:5 separat, poarta și nucleul rămân pe aceeași axă verticală.',
      alt: 'Un observator contemporan integrat într-o incintă minerală din peisajul transilvănean.',
    },
  },
  {
    id: 'gate',
    index: '01',
    navLabel: 'Manifest',
    eyebrow: 'One signal / four responses',
    title: 'Observăm. Protejăm. Imaginăm. Măsurăm.',
    body: 'Nu ne definește o singură tehnologie. Ne definește felul în care transformăm semnale neclare în sisteme care pot fi demonstrate.',
    align: 'right',
    tone: 'brass',
    scrollVh: 130,
    asset: {
      id: 'gate-aperture-detail',
      kind: 'environment',
      status: 'placeholder',
      aspectRatio: '16:10',
      minimumSize: '2400x1500',
      subject: 'Poartă fațetată derivată din marca echipei, cu șase segmente și pivot central.',
      composition: 'Prim-plan fără text sau simbol suplimentar; material mineral deschis, muchii metalice discrete.',
      motionRole: 'Segmentele se deschid reversibil și devin masa workshopului.',
      mobileTreatment: 'Prim-plan frontal; mișcarea se reduce la trei stări clare.',
      alt: 'O poartă mecanică fațetată se deschide în jurul unui pivot central.',
    },
    tags: ['Observe', 'Protect', 'Imagine', 'Measure'],
  },
  {
    id: 'workshop',
    index: '02',
    navLabel: 'Echipa',
    eyebrow: 'Six disciplines / one workshop',
    title: 'Munca se vede în conexiuni.',
    body: 'Șase contribuții distincte se întâlnesc într-un singur sistem. Rolurile finale și proiectele personale rămân marcate pentru validare, fără biografii inventate.',
    align: 'left',
    tone: 'moss',
    scrollVh: 170,
    asset: {
      id: 'workshop-six-stations',
      kind: 'environment',
      status: 'placeholder',
      aspectRatio: '16:10',
      minimumSize: '2400x1500',
      subject: 'Curte-workshop cu exact șase stații și un nucleu comun fațetat.',
      composition: 'Cameră ridicată, lumină de dimineață, calcar și tencuială dominante; fiecare stație are siluetă unică.',
      motionRole: 'Camera orbitează maximum 18 grade; stația selectată se aliniază cu nucleul.',
      mobileTreatment: 'Stațiile devin o succesiune verticală; maximum două vizibile simultan.',
      alt: 'Un atelier în jurul unei curți, cu șase stații conectate la un nucleu comun.',
    },
    metrics: [{ value: '6', label: 'membri', evidence: 'team-confirmed' }],
  },
  {
    id: 'nexus',
    index: '03',
    navLabel: 'Nexus',
    eyebrow: 'Observe / Project Nexus',
    title: 'Antrenat în lumi virtuale. Testat pe date reale.',
    body: 'Project Nexus folosește medii sintetice din Unreal Engine 5 și AirSim pentru a genera date de antrenare destinate detecției aeriene cu YOLOv8.',
    align: 'left',
    tone: 'cyan',
    scrollVh: 210,
    asset: {
      id: 'nexus-synthetic-to-real-sequence',
      kind: 'project',
      status: 'research',
      aspectRatio: '16:10',
      minimumSize: '2400x1500',
      subject: 'Secvență autentică: mediu UE5, segmentare, bounding boxes, validare Stanford Drone Dataset.',
      composition: 'Media ocupă ecranul; textul și metricile stau în DOM, în afara punctelor de interes.',
      motionRole: 'Aperture -> lume sintetică -> două output-uri -> cadru real -> planul Aegis.',
      mobileTreatment: 'Comparație prin wipe controlat; un singur output dominant pe stare.',
      alt: 'Date aeriene sintetice sunt transformate în segmentări și detecții, apoi comparate cu imagini reale.',
    },
    metrics: [
      { value: '11', label: 'scenarii', evidence: 'verified' },
      { value: '~9.500', label: 'imagini', evidence: 'verified' },
      { value: '>140.000', label: 'adnotări automate', evidence: 'verified' },
    ],
    tags: ['Unreal Engine 5', 'AirSim', 'YOLOv8'],
    projectIds: ['project-nexus'],
    href: 'https://docs.google.com/presentation/d/1IFLpSXYsgB3ro6IvawuXEFcsHJaB_8aAPX1dooPD5Xg/edit',
    hrefLabel: 'Prezentarea proiectului',
  },
  {
    id: 'aegis',
    index: '04',
    navLabel: 'Aegis',
    eyebrow: 'Protect / Aegis + SchoolMate',
    title: 'Două produse pentru același context școlar.',
    body: 'Aegis securizează accesul printr-un token QR dinamic, scurt și de unică folosință. SchoolMate tratează separat comunicarea și operațiunile dintre elevi, părinți, profesori, secretariat și poartă.',
    align: 'right',
    tone: 'moss',
    scrollVh: 200,
    asset: {
      id: 'aegis-system-flow',
      kind: 'project',
      status: 'placeholder',
      aspectRatio: '16:10',
      minimumSize: '2400x1500',
      subject: 'Flux autentic elev -> token -> scanare -> validare -> jurnal, urmat de cazul conex SchoolMate.',
      composition: 'Un singur traseu prin spațiu; maximum trei ecrane reale vizibile simultan.',
      motionRole: 'Bounding boxes Nexus devin planul porții; tokenul traversează sistemul și deschide următorul capitol.',
      mobileTreatment: 'Flux vertical în cinci pași, cu ecrane separate 9:16.',
      alt: 'Un cod QR temporar trece de la telefonul elevului prin poartă și este validat de sistem.',
    },
    metrics: [
      { value: '20s', label: 'expirare token QR', evidence: 'verified' },
      { value: '5', label: 'roluri în nucleul Aegis', evidence: 'verified' },
      { value: '2 produse', label: 'Aegis și SchoolMate', evidence: 'verified' },
    ],
    tags: ['Flutter', 'Firebase', 'Cloud Functions', 'QR'],
    projectIds: ['aegis', 'schoolmate'],
    href: 'https://github.com/BosRegele/Aegis',
    hrefLabel: 'Repository Aegis',
  },
  {
    id: 'buried-hands',
    index: '05',
    navLabel: 'Buried Hands',
    eyebrow: 'Imagine / The Buried Hands',
    title: 'O lume se învață prin regulile ei.',
    body: 'Un stealth-puzzle plasat în mausoleul lui Qin Shi Huang. Jucătorul supraviețuiește prin unelte, lumină limitată și înțelegerea mecanismelor, nu prin forță.',
    align: 'left',
    tone: 'mercury',
    scrollVh: 190,
    asset: {
      id: 'buried-hands-gameplay-descent',
      kind: 'video',
      status: 'placeholder',
      aspectRatio: '16:10',
      minimumSize: '2400x1500',
      subject: 'Gameplay autentic cu lampă, coridor, mecanism și risc de detecție.',
      composition: 'Cadru clar și inspectabil, fără trailer montat agresiv sau mockup de monitor.',
      motionRole: 'Planul Aegis devine traseul mausoleului; lumina lămpii dezvăluie sistemele jocului.',
      mobileTreatment: 'Crop vertical dedicat sau secvență de trei cadre, fără text ars în video.',
      alt: 'Un meșteșugar explorează un coridor întunecat luminat de o lampă cu ulei.',
    },
    tags: ['Godot 4', 'GDScript', 'Blender'],
    projectIds: ['the-buried-hands'],
    href: 'https://juggypuggy.itch.io/the-buried-hands',
    hrefLabel: 'Joacă pe itch.io',
  },
  {
    id: 'research',
    index: '06',
    navLabel: 'Research',
    eyebrow: 'Measure / Research',
    title: 'Nu decorăm concluziile. Arătăm metoda.',
    body: 'EconomyNews cercetează relația dintre știri financiare neașteptate, sentiment LLM și reacții intraday. Al doilea proiect evaluează riscul de automatizare al ocupațiilor prin metode de învățare automată.',
    align: 'right',
    tone: 'paper',
    scrollVh: 180,
    asset: {
      id: 'research-evidence-table',
      kind: 'evidence',
      status: 'placeholder',
      aspectRatio: '16:10',
      minimumSize: '2400x1500',
      subject: 'Grafice, fragmente de metodologie și rezultate exportate direct din surse.',
      composition: 'Suprafață editorială luminoasă, fără laptop mockup; graficele au axe și unități complete.',
      motionRole: 'Straturile jocului se aplatizează în hârtie, date și axe măsurabile.',
      mobileTreatment: 'Grafice individuale 4:5 și tabele cu scroll orizontal controlat.',
      alt: 'Grafice și note metodologice din două proiecte de cercetare ale echipei.',
    },
    tags: ['LLM sentiment', 'Intraday analysis', 'Machine learning'],
    projectIds: ['economy-news', 'automation-risk'],
  },
  {
    id: 'archive',
    index: '07',
    navLabel: 'Arhivă',
    eyebrow: 'Archive / Evidence over trophies',
    title: 'Rezultatele au context, dată și dovadă.',
    body: 'Arhiva leagă fiecare clasare de proiect, contribuții și sursa care o confirmă. Intră aici și Chronos CTF, Infect.exe, SchoolMate și milestone-urile echipei.',
    align: 'left',
    tone: 'brass',
    scrollVh: 170,
    asset: {
      id: 'archive-evidence-atlas',
      kind: 'evidence',
      status: 'placeholder',
      aspectRatio: '16:10',
      minimumSize: '2400x1500',
      subject: 'Atlas de dovezi: fotografii, diplome, builds și linkuri, fără trofee 3D inventate.',
      composition: 'Documentele sunt plane fizice în jurul astrolabului; o dovadă dominantă pe stare.',
      motionRole: 'Axe de research devin inelele arhivei; fiecare oprire selectează o intrare.',
      mobileTreatment: 'Timeline vertical cu media full-width și caption imediat sub ea.',
      alt: 'O arhivă cronologică de proiecte, rezultate și documente ale echipei.',
    },
  },
  {
    id: 'join',
    index: '08',
    navLabel: 'Contact',
    eyebrow: 'The system stays open',
    title: 'Următorul semnal poate veni de la tine.',
    body: 'Colaborări, competiții, mentorat și membri noi. Spune-ne ce vrei să construiești și ce poți aduce la masă.',
    align: 'center',
    tone: 'mineral',
    scrollVh: 120,
    asset: {
      id: 'observatory-dawn-exit',
      kind: 'environment',
      status: 'placeholder',
      aspectRatio: '16:10',
      minimumSize: '2400x1500',
      subject: 'Aceeași lume din hero, acum în lumină naturală și cu poarta deschisă.',
      composition: 'Cadru respirabil; nucleul și ieșirea rămân vizibile, fără people compositing.',
      motionRole: 'Astrolabul se închide în marcă; camera părăsește incinta pe aceeași axă de intrare.',
      mobileTreatment: 'Poarta ocupă treimea superioară, CTA-ul rămâne sub linia orizontului.',
      alt: 'Observatorul la răsărit, cu poarta deschisă spre peisaj.',
    },
    href: 'mailto:calin.nedelcu08@gmail.com',
    hrefLabel: 'Scrie-ne',
  },
];

const PROVISIONAL_MEDIA: Record<string, string> = {
  'nexus-synthetic-to-real-sequence': '/assets/projects/project-nexus.webp',
  'nexus-world-contact-sheet': '/assets/projects/project-nexus.webp',
  'nexus-pipeline-proof': '/assets/projects/project-nexus.webp',
  'nexus-real-validation': '/assets/projects/project-nexus.webp',
  'aegis-system-flow': '/assets/projects/aegis.webp',
  'aegis-token-flow': '/assets/projects/aegis.webp',
  'aegis-role-map': '/assets/projects/aegis.webp',
  'schoolmate-product-map': '/assets/projects/schoolmate.webp',
  'schoolmate-workflows': '/assets/projects/schoolmate.webp',
  'buried-hands-gameplay-descent': '/assets/projects/the-buried-hands.webp',
  'buried-hands-player-state': '/assets/projects/buried-hands/guards.webp',
  'buried-hands-system-triptych': '/assets/projects/buried-hands/royal-hall.webp',
  'research-evidence-table': '/assets/projects/research-crossing/economy-event-timeline.webp',
  'economy-news-method': '/assets/projects/research-crossing/economy-pre-post-drift.webp',
  'automation-risk-evidence': '/assets/projects/research-crossing/automation-shap.webp',
  'infect-exe-hero': '/assets/projects/infectexe.webp',
  'infect-exe-loop': '/assets/projects/infect-exe/gpu.png',
};

function sceneAsset(sceneId: SceneId): AssetSlot {
  const scene = SCENES.find((candidate) => candidate.id === sceneId);
  if (!scene) throw new Error(`Unknown scene asset: ${sceneId}`);
  return {
    ...scene.asset,
    previewSrc: PROVISIONAL_MEDIA[scene.asset.id],
  };
}

function placeholderAsset(
  id: string,
  kind: AssetSlot['kind'],
  subject: string,
  composition: string,
  motionRole: string,
  alt: string,
): AssetSlot {
  return {
    id,
    kind,
    status: 'placeholder',
    aspectRatio: '16:10',
    minimumSize: '2400x1500',
    subject,
    composition,
    motionRole,
    mobileTreatment: 'Versiune 4:5 separată; subiectul și dovada principală rămân în centrul cadrului.',
    alt,
    previewSrc: PROVISIONAL_MEDIA[id],
  };
}

export const PROJECTS: ProjectDefinition[] = [
  {
    id: 'project-nexus',
    slug: 'project-nexus',
    index: '01',
    title: 'Project Nexus',
    shortTitle: 'Nexus',
    facets: ['machine-learning'],
    disciplineLabel: 'Machine learning / Computer vision',
    year: 2026,
    state: 'shipped',
    evidence: 'verified',
    featured: true,
    summary: 'Un pipeline care generează date aeriene sintetice în Unreal Engine 5 și le folosește pentru detecția persoanelor cu YOLOv8.',
    thesis: 'Putem transforma o lume controlată într-un laborator pentru situații care sunt rare, scumpe sau greu de adnotat în realitate.',
    tags: ['Unreal Engine 5', 'AirSim', 'YOLOv8', 'Python'],
    accent: 'cyan',
    heroAsset: sceneAsset('nexus'),
    metrics: [
      { value: '11', label: 'scenarii sintetice', evidence: 'verified' },
      { value: '~9.500', label: 'imagini totale', evidence: 'verified' },
      { value: '>140.000', label: 'adnotări automate', evidence: 'verified' },
    ],
    chapters: [
      {
        id: 'context',
        index: '01',
        label: 'Context',
        title: 'Datele sunt problema înainte ca modelul să fie soluția.',
        body: 'Proiectul tratează generarea datasetului ca parte a sistemului, nu ca o etapă ascunsă. Scenele, vremea, orele și poziția dronei pot fi controlate și repetate.',
        asset: placeholderAsset(
          'nexus-world-contact-sheet',
          'evidence',
          'Contact sheet cu cele 11 scenarii autentice din Unreal Engine 5.',
          'Grilă editorială fără mockup de monitor; fiecare scenariu are un identificator scurt.',
          'La scroll, grila se ordonează după vreme și interval orar.',
          'O selecție de medii aeriene sintetice folosite în Project Nexus.',
        ),
      },
      {
        id: 'pipeline',
        index: '02',
        label: 'Pipeline',
        title: 'Captură, segmentare și adnotare în aceeași buclă.',
        body: 'AirSim controlează captura aeriană, iar pipeline-ul produce imaginile și măștile necesare antrenării. Datasetul este împărțit 90% train și 10% validation.',
        asset: placeholderAsset(
          'nexus-pipeline-proof',
          'evidence',
          'Același cadru în trei stări: RGB, segmentare și bounding boxes.',
          'Triptych perfect aliniat; fără crop-uri diferite între stări.',
          'Un wipe controlat de scroll dezvăluie transformările pe același cadru.',
          'Un cadru aerian comparat între imagine, segmentare și detecție.',
        ),
      },
      {
        id: 'validation',
        index: '03',
        label: 'Validation',
        title: 'Lumea sintetică trebuie confruntată cu una reală.',
        body: 'Modelul YOLOv8 este testat atât pe date sintetice, cât și pe Stanford Drone Dataset. Nu publicăm un procent de acuratețe până când valoarea poate fi extrasă din datele sursă.',
        note: 'Limitarea rămâne vizibilă în studiul de caz; nu transformăm un grafic neclar într-o cifră de marketing.',
        asset: placeholderAsset(
          'nexus-real-validation',
          'video',
          'Clipul original de validare pe Stanford Drone Dataset, cu output-ul modelului.',
          'Cadru real inspectabil; overlay-ul păstrează scorurile și clasele lizibile.',
          'Video scrubbable numai în secțiunea activă, cu fallback pe trei cadre statice.',
          'Detecții ale modelului pe o filmare aeriană reală.',
        ),
      },
    ],
    links: [
      {
        label: 'Prezentarea proiectului',
        href: 'https://docs.google.com/presentation/d/1IFLpSXYsgB3ro6IvawuXEFcsHJaB_8aAPX1dooPD5Xg/edit',
        kind: 'presentation',
      },
    ],
    credits: [
      { memberId: 'calin-nedelcu', evidence: 'verified' },
      { memberId: 'andrei-cheroiu', evidence: 'verified' },
      { memberId: 'cristian-buloi', evidence: 'verified' },
      { memberId: 'vlad-colan', evidence: 'verified' },
    ],
  },
  {
    id: 'aegis',
    slug: 'aegis',
    index: '02',
    title: 'Aegis',
    shortTitle: 'Aegis',
    facets: ['school-software'],
    disciplineLabel: 'School software / Safe access',
    year: 2026,
    state: 'shipped',
    evidence: 'verified',
    featured: true,
    summary: 'Un sistem de acces școlar bazat pe un token QR dinamic, scurt și de unică folosință.',
    thesis: 'O interacțiune de câteva secunde la poartă poate rămâne simplă pentru utilizator fără să fie superficială în infrastructură.',
    tags: ['Flutter', 'Firebase', 'Cloud Functions', 'QR'],
    accent: 'moss',
    heroAsset: sceneAsset('aegis'),
    metrics: [
      { value: '20s', label: 'expirare token', evidence: 'verified' },
      { value: 'Single-use', label: 'redeem atomic', evidence: 'verified' },
      { value: '5', label: 'roluri în Aegis', evidence: 'verified' },
    ],
    chapters: [
      {
        id: 'gate-flow',
        index: '01',
        label: 'Core flow',
        title: 'Un cod scurt, un singur drum prin sistem.',
        body: 'Aegis generează un token criptografic temporar, îl prezintă ca QR și îl validează în funcție de rol. După folosire sau expirare, tokenul nu mai poate deschide accesul.',
        asset: placeholderAsset(
          'aegis-token-flow',
          'project',
          'Flux real: emitere token, QR pe telefon, scanare la poartă, rezultat și jurnal.',
          'Cinci stări aliniate pe un singur traseu, cu maximum trei vizibile simultan.',
          'Tokenul traversează traseul în ritmul scroll-ului; fiecare stare rămâne reversibilă.',
          'Etapele prin care un cod QR temporar este validat la poarta școlii.',
        ),
      },
      {
        id: 'roles',
        index: '02',
        label: 'System',
        title: 'Securitatea depinde de rol, nu doar de cod.',
        body: 'Nucleul Aegis separă elevii, părinții, profesorii, administratorii și dispozitivele de acces. Studiul de caz va arăta permisiunile reale, nu ecrane decorative.',
        asset: placeholderAsset(
          'aegis-role-map',
          'evidence',
          'Hartă verificată a celor cinci roluri și a permisiunilor lor.',
          'Diagramă radială simplă, cu etichete complete și trasee fără intersecții inutile.',
          'Rolurile se activează succesiv și converg spre validarea de la poartă.',
          'O hartă a rolurilor și permisiunilor din sistemul Aegis.',
        ),
      },
      {
        id: 'result',
        index: '03',
        label: 'Result',
        title: 'Produsul și rezultatul rămân în același caz.',
        body: 'Aegis a obținut locul 2 la Skills for the Future. Studiul final va lega rezultatul de build, contribuții și sursa oficială, nu de o prezentare izolată a premiului.',
        note: 'Creditele complete pentru faza de concurs sunt încă în validare.',
      },
    ],
    links: [{ label: 'Repository Aegis', href: 'https://github.com/BosRegele/Aegis', kind: 'repository' }],
    credits: [
      { memberId: 'calin-nedelcu', evidence: 'verified' },
      { memberId: 'cristian-buloi', evidence: 'verified' },
      { memberId: 'vlad-bostina', evidence: 'verified' },
      { memberId: 'andrei-cheroiu', evidence: 'verified' },
    ],
  },
  {
    id: 'schoolmate',
    slug: 'schoolmate',
    index: '03',
    title: 'SchoolMate',
    shortTitle: 'SchoolMate',
    facets: ['school-software'],
    disciplineLabel: 'School software / Operations',
    year: 2026,
    state: 'active',
    evidence: 'team-confirmed',
    featured: true,
    summary: 'O platformă pentru anunțuri, cereri, orare și fluxuri între elevi, părinți, profesori și administrație.',
    thesis: 'Software-ul școlar devine util când leagă rolurile și fluxurile zilnice fără să adauge încă un strat de fricțiune.',
    tags: ['Flutter', 'Firebase', 'Education software'],
    accent: 'moss',
    heroAsset: placeholderAsset(
      'schoolmate-product-map',
      'project',
      'Ecrane reale SchoolMate grupate după flux, nu după aspect vizual.',
      'Un ecran dominant și trei stări secundare; toate capturile vin din build.',
      'Planul porții Aegis se extinde într-o hartă de operațiuni școlare.',
      'Interfețe ale platformei SchoolMate organizate pe fluxuri școlare.',
    ),
    chapters: [
      {
        id: 'problem',
        index: '01',
        label: 'Context',
        title: 'Școala nu este un singur flux și nici un singur utilizator.',
        body: 'Studiul de caz va separa nevoile elevilor, părinților, profesorilor și administrației înainte de a prezenta ecranele produsului.',
      },
      {
        id: 'product-map',
        index: '02',
        label: 'Product',
        title: 'Anunțuri, cereri și orare într-un sistem comun.',
        body: 'Capturile finale vor fi organizate după sarcină și rol. Nu atribuim încă funcții sau rezultate care nu pot fi confirmate din build.',
        asset: placeholderAsset(
          'schoolmate-workflows',
          'project',
          'Capturi SchoolMate pentru anunțuri, cereri și orare.',
          'Trei fluxuri lizibile, cu un singur ecran dominant pe fiecare stare.',
          'Fiecare flux pornește din aceeași hartă de roluri și revine în ea.',
          'Trei fluxuri de lucru din aplicația SchoolMate.',
        ),
      },
      {
        id: 'continuity',
        index: '03',
        label: 'Continuity',
        title: 'Aegis și SchoolMate împart domeniul, nu aceeași pagină.',
        body: 'Relația tehnică și cronologică exactă dintre cele două proiecte rămâne în validare. În website sunt studii de caz separate, legate explicit ca proiecte conexe.',
        note: 'Mențiunea de la Hardcore Entrepreneur 6 va fi publicată numai cu formularea și dovada oficială.',
      },
    ],
    links: [
      { label: 'Repository SchoolMate', href: 'https://github.com/calinnedelcu/SchoolMate-final', kind: 'repository' },
    ],
    credits: [],
  },
  {
    id: 'the-buried-hands',
    slug: 'the-buried-hands',
    index: '04',
    title: 'The Buried Hands',
    shortTitle: 'Buried Hands',
    facets: ['video-games'],
    disciplineLabel: 'Video game / Stealth puzzle',
    year: 2026,
    state: 'shipped',
    evidence: 'team-confirmed',
    featured: true,
    summary: 'Un stealth-puzzle în mausoleul lui Qin Shi Huang, în care un meșteșugar supraviețuiește prin lumină, unelte și înțelegerea mecanismelor.',
    thesis: 'Jucătorul nu trebuie să devină mai puternic; trebuie să înțeleagă mai bine lumea în care a fost prins.',
    tags: ['Godot 4', 'GDScript', 'Blender'],
    accent: 'mercury',
    heroAsset: sceneAsset('buried-hands'),
    chapters: [
      {
        id: 'premise',
        index: '01',
        label: 'Premise',
        title: 'Un meșteșugar, nu un războinic.',
        body: 'Personajul este prins în mausoleu în timpul sigilării lui. Lipsa armurii sau a forței mută designul spre observație, evitare și folosirea obiectelor construite chiar de el.',
        asset: placeholderAsset(
          'buried-hands-player-state',
          'video',
          'Gameplay autentic cu personajul, lampa și o decizie clară de stealth.',
          'Cadru wide fără HUD supradimensionat; amenințarea și ruta sunt ambele lizibile.',
          'Scroll-ul modifică numai poziția în secvență; sunetul pornește exclusiv la comandă.',
          'Personajul se deplasează prin mausoleu folosind o lampă cu ulei.',
        ),
      },
      {
        id: 'systems',
        index: '02',
        label: 'Systems',
        title: 'Lumina, pașii și mecanismele devin aceeași problemă.',
        body: 'Lampa are resurse limitate, gărzile pot detecta pașii, iar capcanele și vaporii de mercur schimbă traseul. Fiecare sistem trebuie demonstrat din build în versiunea finală.',
        asset: placeholderAsset(
          'buried-hands-system-triptych',
          'evidence',
          'Trei capturi reale: lumină, detecție prin sunet și mecanism-capcană.',
          'Triptych cu aceeași scară vizuală și captions scurte sub fiecare cadru.',
          'Cele trei sisteme intră pe rând și se suprapun într-un traseu comun.',
          'Trei mecanici de joc din The Buried Hands: lumină, sunet și capcane.',
        ),
      },
      {
        id: 'build',
        index: '03',
        label: 'Build',
        title: 'Un joc public trebuie să poată fi jucat, nu doar descris.',
        body: 'Studiul de caz se încheie cu build-ul public de pe itch.io, creditele complete și o listă onestă de limitări observate după game jam.',
        note: 'Creditele pe rol și dovada clasării vor fi adăugate înainte de publicarea finală.',
      },
    ],
    links: [{ label: 'Joacă pe itch.io', href: 'https://juggypuggy.itch.io/the-buried-hands', kind: 'build' }],
    credits: [],
  },
  {
    id: 'economy-news',
    slug: 'economy-news',
    index: '05',
    title: 'EconomyNews Research',
    shortTitle: 'EconomyNews',
    facets: ['research-paper', 'machine-learning'],
    disciplineLabel: 'Economic research / Machine learning',
    year: 2026,
    state: 'research',
    evidence: 'team-confirmed',
    featured: true,
    summary: 'O cercetare despre știri financiare neașteptate, sentiment extras cu modele lingvistice și reacția intraday a piețelor.',
    thesis: 'O concluzie despre piață are valoare numai dacă evenimentul, fereastra de timp și metoda pot fi urmărite până la sursă.',
    tags: ['LLM sentiment', 'Intraday analysis', 'Python'],
    accent: 'paper',
    heroAsset: sceneAsset('research'),
    metrics: [
      { value: '2.449', label: 'evenimente analizate', evidence: 'team-confirmed' },
      { value: '13 luni', label: 'fereastră de date', evidence: 'team-confirmed' },
      { value: '2', label: 'active urmărite', evidence: 'team-confirmed' },
    ],
    chapters: [
      {
        id: 'question',
        index: '01',
        label: 'Research question',
        title: 'Ce se întâmplă după o știre cu adevărat neașteptată?',
        body: 'Proiectul leagă evenimente financiare, sentiment și mișcări intraday. Ipoteza, universul de date și definiția surprizei vor fi preluate direct din lucrare.',
      },
      {
        id: 'method',
        index: '02',
        label: 'Method',
        title: 'Metoda trebuie să rămână vizibilă lângă rezultat.',
        body: 'Pagina finală va separa colectarea datelor, clasificarea sentimentului și analiza reacției, cu axe, unități și ferestre temporale complete.',
        asset: placeholderAsset(
          'economy-news-method',
          'evidence',
          'Figura metodologică originală și un grafic exportat din analiza sursă.',
          'Suprafață luminoasă; graficul nu este decupat de axe, legendă sau unități.',
          'Etapele metodei se fixează, apoi graficul intră peste aceeași axă.',
          'Metodologia și un rezultat grafic din cercetarea EconomyNews.',
        ),
      },
      {
        id: 'limits',
        index: '03',
        label: 'Limits',
        title: 'Nu completăm golurile cu cifre aproximative.',
        body: 'Studiul separă magnitudinea mișcării de valoarea direcțională a sentimentului și păstrează vizibilă problema latenței feed-ului public.',
        note: 'Rezultatele trebuie citite împreună cu metodologia, baseline-ul și limitările descrise în lucrare.',
      },
    ],
    links: [
      {
        label: 'Lucrarea de cercetare',
        href: 'https://github.com/calinnedelcu/economynewsresearch/blob/main/paper/main.pdf',
        kind: 'paper',
      },
      {
        label: 'Repository și reproducere',
        href: 'https://github.com/calinnedelcu/economynewsresearch',
        kind: 'repository',
      },
    ],
    credits: [],
  },
  {
    id: 'automation-risk',
    slug: 'automation-risk',
    index: '06',
    title: 'Riscul de automatizare al ocupațiilor',
    shortTitle: 'Automation Risk',
    facets: ['research-paper', 'machine-learning'],
    disciplineLabel: 'Labor research / Machine learning',
    year: 2026,
    state: 'research',
    evidence: 'team-confirmed',
    featured: false,
    summary: 'Un proiect de evaluare a riscului de automatizare a ocupațiilor folosind metode de învățare automată.',
    thesis: 'Un scor despre viitorul muncii trebuie explicat prin date, variabile și limite, nu prezentat ca verdict.',
    tags: ['Machine learning', 'Data analysis', 'Python'],
    accent: 'paper',
    heroAsset: sceneAsset('research'),
    metrics: [
      { value: '3.037', label: 'ocupații ESCO', evidence: 'team-confirmed' },
      { value: '654', label: 'ocupații COR mapate', evidence: 'team-confirmed' },
      { value: '14,7%', label: 'acoperire COR', evidence: 'team-confirmed' },
    ],
    chapters: [
      {
        id: 'framing',
        index: '01',
        label: 'Framing',
        title: 'Riscul estimat nu este o sentință.',
        body: 'Studiul de caz va explica ce măsoară modelul, ce nu poate măsura și cum trebuie citite diferențele dintre ocupații.',
      },
      {
        id: 'model',
        index: '02',
        label: 'Model',
        title: 'Datele și variabilele vor preceda clasamentul.',
        body: 'Versiunea finală va include sursa datasetului, pregătirea datelor, modelele comparate și criteriile de evaluare direct din repository.',
        asset: placeholderAsset(
          'automation-risk-evidence',
          'evidence',
          'Un grafic și un tabel exportate direct din notebook sau raport.',
          'Graficul păstrează axele; tabelul arată doar coloanele necesare concluziei.',
          'Tabelul se transformă într-o distribuție fără a modifica ordinea datelor.',
          'Rezultate metodologice din evaluarea riscului de automatizare.',
        ),
      },
      {
        id: 'award-context',
        index: '03',
        label: 'Context',
        title: 'Premiul intră doar împreună cu numele concursului.',
        body: 'Locul 1 este confirmat de echipă, dar numele competiției, categoria, data și dovada rămân în validare înainte de publicare.',
      },
    ],
    links: [
      {
        label: 'Repository',
        href: 'https://github.com/BalaurulBondoc771/Evaluarea-riscului-de-automatizare-a-ocupa-iilor-utiliz-nd-metode-de-nv-are-automat-',
        kind: 'repository',
      },
    ],
    credits: [],
  },
  {
    id: 'infect-exe',
    slug: 'infect-exe',
    index: '07',
    title: 'Infect.exe',
    shortTitle: 'Infect.exe',
    facets: ['video-games'],
    disciplineLabel: 'Video game / 1-bit action',
    year: 2025,
    state: 'shipped',
    evidence: 'verified',
    featured: false,
    summary: 'Un joc 1-bit construit pentru 1-BIT JAM 7, în care jucătorul infiltrează un sistem ca virus și atacă subsistemele lui.',
    thesis: 'O limitare vizuală strictă poate deveni regulă de lume, feedback și identitate în același timp.',
    tags: ['Unity', 'C#', '1-bit'],
    accent: 'mercury',
    heroAsset: placeholderAsset(
      'infect-exe-hero',
      'video',
      'Gameplay autentic din build-ul Infect.exe, fără mockup sau post-procesare cromatică.',
      'Cadru 16:10 cu avatarul, amenințarea și un subsistem lizibile.',
      'Pixelii se desfac în punctele de date ale capitolului Research.',
      'Gameplay alb-negru din jocul Infect.exe.',
    ),
    metrics: [
      { value: '19', label: 'general / 56', evidence: 'verified' },
      { value: '8', label: 'temă', evidence: 'verified' },
      { value: '14', label: 'artă', evidence: 'verified' },
    ],
    chapters: [
      {
        id: 'constraint',
        index: '01',
        label: 'Constraint',
        title: 'Un bit pentru lume și pentru feedback.',
        body: 'Paleta 1-bit nu este tratată ca filtru. Interfața, siluetele, atacurile și lizibilitatea trebuie să funcționeze în aceeași limitare.',
      },
      {
        id: 'loop',
        index: '02',
        label: 'Game loop',
        title: 'Infiltrează. Evită. Distruge subsistemul.',
        body: 'Studiul de caz final va folosi secvențe direct din build pentru a explica bucla de joc, fără capturi reconstituite.',
        asset: placeholderAsset(
          'infect-exe-loop',
          'video',
          'Trei momente consecutive din bucla reală de joc.',
          'Cadru fix; schimbarea vine din starea jocului, nu din mișcarea unui mockup.',
          'Scroll-ul avansează între cele trei momente cu trepte clare.',
          'Trei etape din bucla de joc a Infect.exe.',
        ),
      },
      {
        id: 'result',
        index: '03',
        label: 'Result',
        title: 'Clasarea rămâne legată de pagina oficială.',
        body: 'Jocul a ocupat locul 19 general, locul 8 la temă și locul 14 la artă din 56 de înscrieri la 1-BIT JAM 7.',
      },
    ],
    links: [
      { label: 'Joacă pe itch.io', href: 'https://shieldsentinel.itch.io/infectexe', kind: 'build' },
      { label: 'Rezultatele jam-ului', href: 'https://itch.io/jam/1-bit-jam-7/rate/4068020', kind: 'paper' },
    ],
    credits: [],
  },
];

export const ARCHIVE: ArchiveEntry[] = [
  {
    id: 'nexus-first-place',
    year: 2026,
    title: 'Project Nexus / htechrobotics',
    result: 'Locul 1',
    evidence: 'team-confirmed',
    kind: 'award',
    projectId: 'project-nexus',
    imageSrc: '/assets/achievements/project-nexus-2026.webp',
    imageAlt: 'Echipa Project Nexus pe scenă după obținerea locului întâi.',
  },
  {
    id: 'aegis-skills-future',
    year: 2026,
    title: 'Skills for the Future / Aegis',
    result: 'Locul 2',
    evidence: 'team-confirmed',
    kind: 'award',
    projectId: 'aegis',
    imageSrc: '/assets/achievements/aegis-skills-future-2026.webp',
    imageAlt: 'Finaliștii Skills for the Future 2026 la evenimentul național.',
  },
  {
    id: 'buried-hands-game-jam',
    year: 2026,
    title: 'RDGA x Tudor Vianu Game Jam / The Buried Hands',
    result: 'Locul 2',
    evidence: 'team-confirmed',
    kind: 'award',
    projectId: 'the-buried-hands',
  },
  {
    id: 'automation-risk-first-place',
    year: 2026,
    title: 'Evaluarea riscului de automatizare',
    result: 'Locul 1',
    evidence: 'team-confirmed',
    kind: 'award',
    projectId: 'automation-risk',
    note: 'Concursul, categoria și dovada trebuie confirmate.',
  },
  {
    id: 'schoolmate-hardcore-entrepreneur',
    year: 2026,
    title: 'Hardcore Entrepreneur 6 / SchoolMate',
    result: 'Mențiune',
    evidence: 'team-confirmed',
    kind: 'award',
    projectId: 'schoolmate',
  },
  {
    id: 'chronos-ctf-juniors',
    year: 2025,
    title: 'Chronos Security CTF / Juniors',
    result: 'Locul 3',
    evidence: 'team-confirmed',
    kind: 'ranking',
    imageSrc: '/assets/achievements/chronos-ctf-2025.webp',
    imageAlt: 'Certificatul locului trei la categoria Juniors a Chronos Security CTF 2025.',
  },
  {
    id: 'infect-exe-one-bit-jam',
    year: 2025,
    title: '1-BIT JAM 7 / Infect.exe',
    result: 'Locul 19 general',
    evidence: 'verified',
    kind: 'ranking',
    projectId: 'infect-exe',
    href: 'https://itch.io/jam/1-bit-jam-7/rate/4068020',
    note: 'Locul 8 la temă și locul 14 la artă, din 56 de înscrieri.',
    imageSrc: '/assets/achievements/1bit-jam-7-2025.webp',
    imageAlt: 'Tabelul clasării Infect.exe la 1-BIT JAM 7.',
  },
  {
    id: 'economy-news-siat',
    year: 2026,
    title: 'Joseph Schumpeter, ediția a II-a / EconomyNews',
    result: 'Mențiune',
    evidence: 'verified',
    kind: 'award',
    projectId: 'economy-news',
    note: 'Concurs de comunicări științifice în domeniul economiei.',
    imageSrc: '/assets/projects/siat-diploma.webp',
    imageAlt: 'Diploma obținută de EconomyNews la concursul Joseph Schumpeter.',
  },
  {
    id: 'deutsche-bank-internship',
    year: 2026,
    title: 'Deutsche Bank',
    result: 'Internship',
    evidence: 'team-confirmed',
    kind: 'milestone',
    note: 'Participanții și perioada trebuie confirmați înainte de publicare.',
  },
];

export const sceneById = Object.fromEntries(SCENES.map((scene) => [scene.id, scene])) as Record<
  (typeof SCENES)[number]['id'],
  (typeof SCENES)[number]
>;

export const projectBySlug = Object.fromEntries(PROJECTS.map((project) => [project.slug, project])) as Record<
  string,
  ProjectDefinition
>;

export const projectById = Object.fromEntries(PROJECTS.map((project) => [project.id, project])) as Record<
  ProjectDefinition['id'],
  ProjectDefinition
>;
